#!/bin/bash

MIN_TIME="7200"
min_hour=$(echo "$MIN_TIME / 3600" | bc)

lastsync=$(sudo qlop --sync | tail -n 1)
lastsync=${lastsync:0:19}
lastsync=$(date -d"$lastsync" +%s)
elapsed=$(echo "$(date +%s) - $lastsync" | bc)
flag=$(echo "$elapsed >= $MIN_TIME" | bc)

h=$(echo "$elapsed/3600" | bc)
m=$(echo "$elapsed%3600/60" | bc)
s=$(echo "$elapsed%60" | bc)
hms="$h hours, $m minutes, $s seconds"

if [[ $flag == '1' ]]; then
        echo "Last sync was $hms ago."
	echo "Portage has not been synced within $min_hour hours."
	echo -e "\nSyncing portage...\n"
	sleep 2
	
	sudo emerge --sync
	
	if [[ -z $1 ]]; then
		sudo emerge -uNDtav @world
		sudo emerge --depclean -av
	fi
else
	echo "Portage was synced within $min_hour hours."
	echo "Last sync was $hms ago."

fi
